-- Reader user
GRANT USAGE ON SCHEMA public TO reader_user;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO reader_user;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO reader_user;

REVOKE INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public FROM reader_user;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM reader_user;

-- Writer user
GRANT USAGE ON SCHEMA public TO writer_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO writer_user;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO writer_user;